### ISSUE TITLE
iframe restricted

### ISSUE THREAD

**Issue by ShoGinn** [causefx/iDashboard-PHP#26]
So as I have seen in other issue's; I wanted to create an actionable issue that each one can be addressed appropriately.

pi-hole and some of the ubiquity apps do not allow for iframe  (ubiquity unifi app = same origin and pi-hole = deny).

So I think a good solution is to do what muximux did and do a landing page?

except rather than do a _self direction do "new window" and that should solve these problems.

Maybe i'm being selfish for this request, but I like using this dashboard as a one stop shop for my home devices ;)

**Comment by causefx** [comment]
hmmm, or maybe... I can have it load, and if the page is empty, it can open the same link in a new window...  I think that may work.

**Comment by ShoGinn** [comment]
I give you artistic freedom on this avenue.. if you can somehow see the error (ignorance on my part) and do that it would be even better!

**Comment by causefx** [comment]
i'll look into it

**Comment by ShoGinn** [comment]
@causefx thanks for spending the time!

**Comment by causefx** [comment]
no worries, :)

**Comment by leram84** [comment]
I'll make this comment here since this is where it started, but this is regarding organizr since thats the one i think ill end up using and the one that actually has this feature. Anyway, my question is, having it open another tab is great, and will help for sites blocking iframes. BUT could you also use this feature to fix sites that only block iframes in the login page (tumblr, and hipchat are the first that come to mind). So that when those tabs are opened, instead of opening up a new tab and being done, organizr would open a pop up window of the login page that allows you to log in (in the sameorigin) and then have that page autoclose as soon as your credentials are accepted, bringing you back to the tab in organizr that should now be logged in. Is this possible?

**Comment by causefx** [comment]
Honestly, I don't even know if that is possible.  Let me think about it.

**Comment by ShoGinn** [comment]
I moved on to https://github.com/causefx/Organizr as well; vastly superior ;)
